const skillLevelLabel = (skillLevel) => (skillLevel === 'BEGINNER' ? 'Beginner-friendly' : 'Professional');

/**
 * Resolves concrete design tokens from the approved design_brief.
 * Falls back to ZAIRE's default dark HUD aesthetic if no brief is provided.
 * This is the canonical token resolver — every downstream generator must use this
 * instead of hardcoding colors or fonts per file.
 */
function resolveDesignTokens(designBrief = null) {
  const tokens = designBrief?.visual_tokens || {};
  return {
    primaryColor:  tokens.primary_color        || '#00d4ff',
    neutralScale:  tokens.neutral_scale        || 'zinc',
    displayFont:   tokens.typography?.display  || 'Inter',
    bodyFont:      tokens.typography?.body     || 'Inter',
    borderRadius:  tokens.border_radius        || '12px',
    spacingSystem: tokens.spacing_system       || '8px base',
    bgColor:       tokens.bg_color             || '#050505',
    surfaceColor:  tokens.surface_color        || 'rgba(255,255,255,0.04)',
    borderColor:   tokens.border_color         || 'rgba(255,255,255,0.1)',
  };
}

/**
 * Returns image strategy guidance from the design_brief.
 * Used to annotate generated files with the correct asset approach, preventing
 * generic stock photos from creeping in.
 */
function resolveImageGuidance(designBrief = null) {
  const img = designBrief?.image_strategy || {};
  return {
    heroRole:    img.hero_role    || 'Abstract geometric or product screenshot',
    productRole: img.product_role || 'Actual UI screenshot or mockup',
    avoid:       (img.forbidden_imagery || []).join('; ') || 'Generic stock photos of people at laptops'
  };
}

/**
 * Builds the static scaffold support files for a generated project.
 * @param {Object} plan        - The approved architecture plan
 * @param {Object} intake      - Raw project intake answers
 * @param {string} skillLevel  - 'BEGINNER' | 'PROFESSIONAL'
 * @param {Object} designBrief - The approved design_brief from DB (optional, defaults to ZAIRE HUD style)
 */
function buildEngineerSupportFiles(plan, intake = {}, skillLevel = 'PROFESSIONAL', designBrief = null) {
  const planData = {
    appName: plan.appName,
    normalizedName: plan.normalizedName,
    summary: plan.summary,
    stack: plan.stack || [],
    pages: plan.pages || [],
    components: plan.components || [],
    apiRoutes: plan.apiRoutes || [],
    databaseSchema: plan.databaseSchema || [],
    authFlow: plan.authFlow || '',
    paymentFlow: plan.paymentFlow || '',
    envVars: plan.envVars || [],
    risks: plan.risks || [],
    assumptions: plan.assumptions || [],
    workflowPhases: plan.workflowPhases || [],
    buildChecklist: plan.buildChecklist || [],
    deploymentPlan: plan.deploymentPlan || []
  };

  const planJson = JSON.stringify(planData, null, 2);

  // ── Resolve design tokens from approved design_brief ──────────────────────
  const dt = resolveDesignTokens(designBrief);
  const imgGuide = resolveImageGuidance(designBrief);

  const designBriefSummary = JSON.stringify({
    competitive_category:  designBrief?.competitive_analysis?.category || 'unknown',
    primary_color:         dt.primaryColor,
    neutral_scale:         dt.neutralScale,
    display_font:          dt.displayFont,
    body_font:             dt.bodyFont,
    border_radius:         dt.borderRadius,
    spacing_system:        dt.spacingSystem,
    motion_level:          designBrief?.motion_spec?.level || 'moderate',
    allowed_effects:       designBrief?.motion_spec?.allowed_effects   || [],
    forbidden_effects:     designBrief?.motion_spec?.forbidden_effects  || [],
    image_hero_role:       imgGuide.heroRole,
    image_avoid:           imgGuide.avoid,
    conversion_checklist:  designBrief?.conversion_checklist || []
  }, null, 2);

  const navLinksJson = JSON.stringify([
    { href: '/', label: 'Home' },
    { href: '/dashboard', label: 'Dashboard' },
    { href: '/architecture', label: 'Architecture' },
    { href: '/build', label: 'Build' },
    { href: '/qa', label: 'QA' },
    { href: '/deploy', label: 'Deploy' }
  ], null, 2);
  const modeLabel = skillLevelLabel(skillLevel);

  return {
    'lib/engineer-plan.ts': {
      content: `// AUTO-GENERATED by ZAIRE Engineer Mode — do not edit manually.\n// Design tokens are resolved from the approved design_brief and baked in at build time.\nexport const engineerPlan = ${planJson} as const;\n\n// Resolved design tokens — reference these everywhere instead of hardcoding colors/fonts.\n// Regenerate via ZAIRE Engineer Mode > Design Brief to update.\nexport const designTokens = ${designBriefSummary} as const;\n`,
      explanation: {
        what: 'A single source of truth for the generated engineer project.',
        why: 'Pages and components can read the same plan data without duplication.',
        edit: 'Update this only if the generated architecture changes.',
        protect: 'Keep the object shape aligned with the generated routes and components.'
      }
    }
  };
}

module.exports = {
  buildEngineerSupportFiles,
  resolveDesignTokens,
  resolveImageGuidance
};
