/**
 * github_export_service.js
 *
 * Exports a ZAIRE project to a new GitHub repository using the GitHub REST API.
 * No git binary or local clone is required — files are pushed directly via the
 * GitHub Contents API (PUT /repos/{owner}/{repo}/contents/{path}).
 *
 * Required token scope: `repo` (for private repos) or `public_repo` (for public).
 */

const GITHUB_API = 'https://api.github.com';

/**
 * @typedef {Object} GitHubExportResult
 * @property {string} repoUrl      - HTTPS URL of the created repository
 * @property {string} cloneUrl     - Git clone URL
 * @property {string} owner        - GitHub username / org
 * @property {string} repoName     - Repository name used
 * @property {number} filesUploaded - Number of files successfully pushed
 */

/**
 * Fetches the authenticated GitHub user login from a token.
 * @param {string} token - GitHub personal access token
 * @returns {Promise<string>} GitHub username
 */
async function getGitHubUser(token) {
  const res = await fetch(`${GITHUB_API}/user`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28'
    }
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub auth failed (${res.status}): ${text}`);
  }
  const data = await res.json();
  return data.login;
}

/**
 * Creates a new GitHub repository.
 * @param {string} token      - GitHub PAT
 * @param {string} repoName   - Desired repository name (will be sanitized)
 * @param {boolean} isPrivate - Whether the repo should be private
 * @returns {Promise<{ fullName: string, cloneUrl: string, htmlUrl: string }>}
 */
async function createRepo(token, repoName, isPrivate = true) {
  const res = await fetch(`${GITHUB_API}/user/repos`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      name: repoName,
      description: 'Generated by ZAIRE Engineer Mode',
      private: isPrivate,
      auto_init: false  // We push files manually so we control the initial commit
    })
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub repo creation failed (${res.status}): ${text}`);
  }

  const data = await res.json();
  return {
    fullName: data.full_name,    // e.g. "username/my-project"
    cloneUrl: data.clone_url,
    htmlUrl: data.html_url
  };
}

/**
 * Creates the initial commit on a repo by pushing a placeholder README,
 * which initialises the default branch so files can be committed on top.
 * @param {string} token
 * @param {string} owner
 * @param {string} repo
 * @param {string} [branch]
 */
async function initDefaultBranch(token, owner, repo, branch = 'main') {
  // Push a tiny README to create the branch/tree root
  const res = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/README.md`, {
    method: 'PUT',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      message: 'chore: initialise repository via ZAIRE Engineer Mode',
      content: Buffer.from(`# ${repo}\n\nGenerated by [ZAIRE](https://zaire.ai) Engineer Mode.\n`).toString('base64'),
      branch
    })
  });

  if (!res.ok) {
    const text = await res.text();
    // 422 usually means the file already exists — safe to ignore on re-push
    if (res.status !== 422) {
      throw new Error(`GitHub branch init failed (${res.status}): ${text}`);
    }
  }
}

/**
 * Uploads a single file to the repository using the Contents API.
 * @param {string} token
 * @param {string} owner
 * @param {string} repo
 * @param {string} filePath   - Relative path within the repo (e.g. 'src/index.ts')
 * @param {string} content    - Raw file content string
 * @param {string} [branch]
 * @returns {Promise<boolean>} true if uploaded, false if skipped
 */
async function uploadFile(token, owner, repo, filePath, content, branch = 'main') {
  // Normalise path: strip leading slashes
  const safePath = filePath.replace(/^\/+/, '');
  if (!safePath) return false;

  // The Contents API requires base64-encoded content
  const encodedContent = Buffer.from(String(content ?? '')).toString('base64');

  const res = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/${encodeURIComponent(safePath)}`, {
    method: 'PUT',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      message: `feat: add ${safePath} via ZAIRE scaffold`,
      content: encodedContent,
      branch
    })
  });

  if (!res.ok) {
    const text = await res.text();
    console.warn(`[GITHUB EXPORT] Failed to upload ${safePath} (${res.status}): ${text.slice(0, 200)}`);
    return false;
  }

  return true;
}

/**
 * Sanitizes a project name into a valid GitHub repo name.
 * @param {string} name
 * @returns {string}
 */
function sanitizeRepoName(name) {
  return String(name || 'zaire-project')
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^[-_.]+|[-_.]+$/g, '')
    .slice(0, 100) || 'zaire-project';
}

/**
 * Exports a full project to a new GitHub repository.
 *
 * Files are uploaded serially (not in parallel) to stay well within GitHub's
 * API rate limits (5000 requests/hour for authenticated users).
 *
 * @param {string} projectName   - Human-readable project name (will be sanitized)
 * @param {Array<{path: string, content: string}>} files - Project files
 * @param {string} token         - GitHub personal access token
 * @param {boolean} [isPrivate]  - Whether to create a private repo (default: true)
 * @returns {Promise<GitHubExportResult>}
 */
async function pushToGitHub(projectName, files, token, isPrivate = true) {
  if (!token || !token.trim()) {
    throw new Error('GitHub token is required for export.');
  }
  if (!files || !files.length) {
    throw new Error('No files to export to GitHub.');
  }

  const repoName = sanitizeRepoName(projectName);

  // 1. Resolve the authenticated user
  const owner = await getGitHubUser(token);

  // 2. Create the repository
  const { fullName, cloneUrl, htmlUrl } = await createRepo(token, repoName, isPrivate);
  console.log(`[GITHUB EXPORT] Created repo: ${fullName}`);

  // 3. Initialise the default branch with a placeholder commit
  await initDefaultBranch(token, owner, repoName);

  // 4. Upload every project file — skip the README we just created (it gets overwritten
  //    if the project has its own README.md, which is the intended behaviour)
  let filesUploaded = 0;
  for (const file of files) {
    if (!file.path || file.content === undefined || file.content === null) continue;
    const uploaded = await uploadFile(token, owner, repoName, file.path, file.content);
    if (uploaded) filesUploaded += 1;
  }

  console.log(`[GITHUB EXPORT] Pushed ${filesUploaded}/${files.length} files to ${fullName}`);

  return {
    repoUrl: htmlUrl,
    cloneUrl,
    owner,
    repoName,
    filesUploaded
  };
}

module.exports = {
  pushToGitHub,
  sanitizeRepoName,
  getGitHubUser
};
